In [1]:
import pandas as pd
import numpy as np
import seaborn
import matplotlib
data = pd.read_csv('/Users/lin/Desktop/personal/training_data.csv')
Bots = data[data.bot==1]
NonBots = data[data.bot==0]

'''
seaborn.heatmap(data.isnull(), yticklabels=False, cbar=False, cmap='viridis')
# 热力图，当data中有空值时标为黄色
matplotlib.pyplot.tight_layout()
matplotlib.pyplot.show()

'''

bag_of_words_bot = r'bot|b0t|cannabis|tweet me|mishear|follow me|updates every|gorilla|yes_ofc|forget' \
r'expos|kill|bbb|truthe|fake|anony|free|virus|funky|RNA|jargon'\
r'nerd|swag|jack|chick|prison|paper|pokem|xx|freak|ffd|dunia|clone|genie|bbb' \
r'ffd|onlyman|emoji|joke|troll|droop|free|every|wow|cheese|yeah|bio|magic|wizard|face|papers'

# 该列的每个值包不包含脏话，包含则为True，不包含则为False
data['screen_name_binary'] = data.screen_name.str.contains(bag_of_words_bot, case=False, na=False)
data['name_binary'] = data.name.str.contains(bag_of_words_bot, case=False, na=False)
data['description_binary'] = data.description.str.contains(bag_of_words_bot, case=False, na=False)
data['status_binary'] = data.status.str.contains(bag_of_words_bot, case=False, na=False)

# 判断该列的每个值是否有listedcount>20000的情况，有的话为False，没有的话为True
data['listed_count_binary'] = (data.listedcount > 20000) == False

# 判断该列的每个值是否有空的情况，有空的则为False，否则为True
data['location_binary'] = ~data.location.isnull()
data['url_binary'] = ~data.url.isnull()

# 选定我们的特征
features = ['screen_name_binary', 'name_binary', 'description_binary', 'status_binary', 'verified', 'followers_count',
            'verified', 'friends_count', 'statuses_count', 'listed_count_binary', 'bot', 'url_binary',
            'location_binary', 'default_profile', 'default_profile_image']

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
X = data[features].iloc[:,:-1]
# 除了最后一列的BOT都是数据
y = data[features].iloc[:,-1]
# BOT是分类对象，1：机器人 0：非机器人X_train
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
random_state=101)

clf = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=50, min_samples_split=10)
clf.fit(X_train, y_train)
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)
print("Training Accuracy: %.5f" %accuracy_score(y_train, y_pred_train))
print("Test Accuracy: %.5f" %accuracy_score(y_test, y_pred_test))

Training Accuracy: 0.96117
Test Accuracy: 0.94405

In [2]:
X_test

,screen_name_binary,name_binary,description_binary,status_binary,verified,followers_count,verified,friends_count,statuses_count,listed_count_binary,bot,url_binary,location_binary,default_profile
2409,False,False,False,False,False,32,False,54,16,True,0,False,False,True
416,False,False,True,False,False,1474799,False,1,20990,True,1,True,False,False
1193,False,False,False,False,False,2,False,492,79,True,1,False,True,True
1970,False,False,True,False,False,5273,False,293,6636,True,0,True,True,False
1854,False,False,False,True,True,5766,True,333,358,True,0,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,False,False,False,False,False,1,False,253,26,True,1,False,True,True
1834,False,False,False,False,False,1780,False,820,1827,True,0,True,True,False
1932,False,False,False,False,True,513333,True,243,1707,True,0,True,False,False
213,True,False,True,True,False,6027,False,0,116980,True,1,True,True,False
110,False,False,False,False,False,1,False,420,80,True,1,False,True,True

In [4]:
user = pd.read_excel('/Users/lin/Desktop/personal/mydata/tweet_comment.xlsx')

In [6]:
user.head()

,m_origin_id,u_id,r_id,r_content,g_publish_time,u_nickname,u_url,u_introduction,r_follow_num,r_fans_num,verified,u_login_time,u_area
0,1043334390850510849,24928470,1044083498854895618,"@1DLowther @dcpoll @CNN Not tht I know of,",2018-09-24 12:37:58,yvonne,https://twitter.com/animalfriend1,"Veterinary Professional,animal supporter,Scien...",2693.0,2089.0,0.0,2009-03-18 02:37:59,Fl
1,1043334390850510849,140166872,1043367165749915648,@BabyD_Rae @dcpoll @power2she @CNN They don't ...,2018-09-22 13:11:31,immigration detention = $770/night squalor,https://twitter.com/pookietooth,"gov't should regulate co's & protect us, not p...",8305.0,7332.0,0.0,2010-05-05 03:41:28,United States
2,1043334390850510849,308698101,1043353604499955712,@DwayneRude1 @dcpoll @CNN LMFAOOOOOOOOOOOO,2018-09-22 12:17:38,❄VerySpecialSnowFlake❄,https://twitter.com/miamidecor,Snowflake in Miami,7900.0,7028.0,0.0,2011-06-01 05:06:40,Stalking Zimmerman
3,1043334390850510849,831816535,1043340238893068288,@Enrico056 @dcpoll @CNN @GOP @ChuckGrassley Th...,2018-09-22 11:24:31,Patty Harbison,https://twitter.com/PattyHarbison,"#TodaysHaiku Retired lawyer, HLS alum. Wife to...",964.0,1291.0,0.0,2012-09-19 04:20:37,Middle TN
4,1043334390850510849,833728731504013312,1043344963507867648,@KitchyItchy @dcpoll @CNN His weird little fla...,2018-09-22 11:43:18,A Middle Aged Lady in a Flyover State,https://twitter.com/AFlyover,I've installed a Xanax Salt Lick in every room...,4270.0,4205.0,0.0,2017-02-21 01:23:14,Middle of Nowhere

In [ ]:
# 该列的每个值包不包含脏话，包含则为True，不包含则为False
user['screen_name_binary'] = user.u_nickname.str.contains(bag_of_words_bot, case=False, na=False)
user['name_binary'] = data.u_nickname.str.contains(bag_of_words_bot, case=False, na=False)
user['description_binary'] = data.u_introduction.str.contains(bag_of_words_bot, case=False, na=False)
data['status_binary'] = data.status.str.contains(bag_of_words_bot, case=False, na=False)